# Generated by Django 3.2 on 2021-04-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.business')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('width', models.FloatField()),
                ('deep', models.FloatField()),
                ('aviable', models.BooleanField()),
                ('rent', models.FloatField()),
                ('administration', models.FloatField()),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.business')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.category'),
        ),
    ]
