# Generated by Django 3.2 on 2021-05-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
