# Generated by Django 3.2 on 2021-05-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_auto_20210513_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.product', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
