# Generated by Django 3.2 on 2021-05-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_auto_20210513_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='local',
            name='administration',
            field=models.FloatField(verbose_name='Administracion'),
        ),
        migrations.AlterField(
            model_name='local',
            name='aviable',
            field=models.BooleanField(verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='local',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.business'),
        ),
        migrations.AlterField(
            model_name='local',
            name='deep',
            field=models.FloatField(verbose_name='Profundidad'),
        ),
        migrations.AlterField(
            model_name='local',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='local',
            name='rent',
            field=models.FloatField(verbose_name='Arrendo'),
        ),
        migrations.AlterField(
            model_name='local',
            name='width',
            field=models.FloatField(verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.business', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
